import Head from 'next/head'
import '../styles/globals.css'
import { Provider } from 'next-auth/client'
function MyApp({ Component, pageProps }) {


  return (
    <Provider>
      <Head>
        <title>Auth demon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/
        " />
      </Head>
      <div>
        <Component {...pageProps} />
      </div>
    </Provider>
  )
}

export default MyApp
